def questions(index):
    quest = ["What are the names of the certification schemes analyzed in the report?",
"Do these certification schemes comply with national or EU legislation (e.g., RED II)?",
"Who are the holders/owners of each certification scheme?",
"Which accreditation bodies oversee these certification schemes?",
"What are the off-take applications for each certification scheme (regulatory/compliance market vs. voluntary/reporting market)?",
"What type of certificates do these schemes issue (Energy Attribute Certificates or Sustainability Certificates)?",
"Which body issues the certificates if different from the certification body?",
"Which organizations act as certification bodies and conduct audits?",
"Which types of fuels are covered by these certification schemes (Hydrogen, Ammonia, Methanol, SAF, Biofuels, e-NG)?",
"What is the geographic coverage of each certification scheme?",
"Do the certification schemes follow specific standards (e.g., ISO)?",
"How is labeling handled? What labels are used (e.g., Green Hydrogen, Low Carbon Hydrogen)?",
"How applicable are these certification schemes across different markets?",
"What phases of the lifecycle do these certification schemes cover (Cradle-to-gate, Cradle-to-wheel, etc.)?",
"What is the comparator value used in these certification schemes for CO₂ emissions (in grams)?",
"What is the minimum GHG reduction target required by each certification scheme (percentage)?",
"What methodology is used for Product Carbon Footprint (PCF) calculation?",
"How frequently is PCF calculated (single time vs. multiple times during the lifecycle)?",
"What are the requirements for dedicated CO₂ sources under each certification scheme?",
"What energy sources are required for certification (percentage of renewable energy)?",
"What hydrogen production technologies are eligible (Electrolysis, Steam Methane Reforming, etc.)?",
"What chain of custody models do these certification schemes use (Book and Claim, Mass Balance Tracking, etc.)?",
"How is traceability ensured? Where is the certificate tracked (digital registry, blockchain, etc.)?",
"How transparent are the certification schemes? Are certification documents publicly accessible?"]
    return quest[index]